name = "SCSS Bootstrap"
license = "MIT"
licenselink = "https://github.com/obar/bootstrap-scss-hugo-theme/blob/master/LICENSE"
description = "A simple Bootstrap theme for Hugo using SCSS"
homepage = "https://github.com/obar/scss-bootstrap-hugo-theme"
tags = ["home", "blog", "tags", "bootstrap", "minimal", "clean", "simple", "feather"]
features = ["home", "blog", "tags", "bootstrap", "minimal", "clean", "simple", "feather"]
min_version = "0.60.1"

[author]
  name = "Ori Barbut"
  homepage = "http://www.oribarbut.com/"
